matrix:
  include:
    - language: python
      python:
        - "2.7"
        - "3.6"      # current default Python on Travis CI
      install:
        - pip install -r requirements.txt
      script:
        - python easinGenerator.py  -c examples/config.yaml
    - language: node_js
      python:        
        - "2.7"  
      install:
        - pip install -r requirements.txt
      script:
        - python easinGenerator.py  -c examples/config.yaml
        - npm install
        - npm run buildTemplates
        - npm run test
