language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
virtualenv:
  system_site_packages: true
script:
    - python easinGenerator.py  -c examples/config.yaml
    - npm install
    - npm run buildTemplates
    - npm run test
    - cd serverTest-0.0.1-SNAP/
    - ls -alh 
    - mvn package
    - mvn install