---
project:
  longname: Easy Soft IN Selling Server
  description: Easin Selling Server
  url: http://easysoft-in.com
  name: serverTest
  restPath: /serverTest
  package: com.easin.serverTest
  version: 0.0.1-SNAP
  security:
    extraroles: # please do not prefix roles with ROLE_ !      
      - "PROVIDER"
      - "CONSUMER"
    # from now security is activated always and cannot be disactivated
    # by default access is GRANTED for all entity for all roles
    # can be changes once the code is generated     
database:
  test:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    dialect: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    username: easin
    password: ''
    ddlauto: create
  dev:
    url: jdbc:h2:/tmp/sbr-gen-database.h2;DB_CLOSE_ON_EXIT=FALSE
    dialect: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    username: easin
    password: ''
    ddlauto: update
  prod:
    url: jdbc:postgresql://localhost:5432/essDB
    dialect: org.hibernate.dialect.PostgreSQL82Dialect
    driverClassName: org.postgresql.Driver
    username: easin
    password: Easin
    ddlauto: update
logging:
  RootLoggerLevel: INFO
  Loggers:
    - name: com.easin
      level: trace
    - name: org.springframework.web.client.RestTemplate
      level: trace
    - name: org.apache.catalina.filters.RequestDumperFilter
      level: trace
entities:
  - name: User
    comment: Class representing the User parameters
    fields:
      - name: mail
        type: String
        comment: the official Mail of the User
        annotations:
          - "@Email"
      - name: phone
        type: String
        comment: the official Phone number of the User
        annotations:  []
      - name: name
        comment: name of the User
        annotations:
          - "@Column(nullable = false)"
        type: String
  - name: Company        
    comment: Class representing the company parameters
    fields:
      - name: owner
        comment: User Owner  of the comapny
        annotations:
          - "@ManyToOne"          
        type: User      
      - name: mail
        type: String
        comment: the official Mail of the company
        annotations:
          - "@Email"
      - name: phone
        type: String
        comment: the official Phone number of the company
        annotations:  []
      - name: tvaRate
        type: Integer
        comment: tva Rate of the Company
        annotations:
          - "@Column(nullable = false)"
          - '@Min(value = 0L, message = "The value must be positive")'
          - '@Max(value = 50L, message = "The value must lesser than 50")'
      - name: tvaCode
        type: String
        comment: tva Code of the Company
        annotations:
          - "@Column(nullable = false)"
      - name: name
        comment: name of the Company
        annotations:
          - "@Column(nullable = false)"
        type: String
  - name: Address    
    comment: Class representing the Address parameters
    fields:
      - name: address
        comment: address of the Company
        annotations:
          - "@Column(nullable = false)"
        type: String
      - name: zipcode
        comment: zipcode of the Company
        annotations:
          - "@Column(nullable = false)"
        type: Integer
      - name: town
        comment: town of the Company
        annotations:
          - "@Column(nullable = false)"
        type: String
      - name: contry
        comment: contry of the Company
        annotations:
          - "@Column(nullable = false)"
        type: String


